### ISSUE TITLE
LOOT failed to load, load order/Plugins

### ISSUE THREAD

**Issue by BiggerNERD** [loot/loot.github.io#122]
![image_2024-04-08_120024912](https://github.com/loot/loot.github.io/assets/166437316/491e752b-184c-45bd-926b-f68443a4ee50)

I am mostly new to modding a Bethesda game, and have been following steps very carefully
This problem infinitely happens when I open the application. I did the install steps for LOOT/Vortex and MO2. It seems that LOOT is the only program having issues looking for the plugin list/load order.
I have searched this problem up online and none of the solutions were helpful. 
The Unofficial Tutorial on the LOOT page skips over this entirely unfortunately.

**Comment by pStyl3** [comment]
Please provide your LOOTDebugLog.txt according to [Supplying Debug Logs For Application Issues](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html#supplying-log).

**Comment by BiggerNERD** [comment]
Thanks for the attempt. Im deleting everything and starting over.
