### ISSUE TITLE
Asian Charakters in General Messages

### ISSUE THREAD

**Issue by Equilibrior** [loot/loot.github.io#35]
In the "General Messages" Corner of the Summary Page are all Messages written with Asian Charakter, although my Language Settings are German.
![unbenannt](https://cloud.githubusercontent.com/assets/2765538/5792315/231c86ba-9f13-11e4-9ddc-48fea058736e.JPG)

**Comment by WrinklyNinja** [comment]
OK, I can replicate this in v0.6.1, it looks like I didn't properly fix messages being displayed using the wrong language in that release. The issue isn't present in the v0.7.0 beta though.
