### ISSUE TITLE
Revenge of the Enemies = Load After

### ISSUE THREAD

**Issue by GamerPoets** [loot/loot.github.io#36]
The mod Revenge of the Enemies... (link below)
http://www.nexusmods.com/skyrim/mods/40491

...specifies on it's page that it should load after the Skyrim Redone. SkyRe_EnemyAI.esp so that it can function properly. However, LOOT does not load it this way. And when I try to do the "load after" myself, SkyRe_EnemyAI does not show up as a conflict for me to do so.

**Comment by WrinklyNinja** [comment]
Looking in TES5Edit, there is indeed no conflict between `Rebirth Monster.esp` and `SkyRe_EnemyAI.esp`, so LOOT is working correctly.

Also, in future, game-specific bug reports should be filed in their masterlist repository, eg. [loot/skyrim](https://github.com/loot/skyrim).
