### ISSUE TITLE
Consistantly allows Cooking / Food Mods to load After RND

### ISSUE THREAD

**Issue by mikeloeven** [loot/loot.github.io#37]
The sorting system needs to load Realistic needs and Diseases and it's associated Compatibility patches After any and all cooking or food mods otherwise the majority of food in the game will not be able to restore hunger and thirst. Currently LOOT doesent do this and while the RND patches will load after the cooking mods they are associated with the cooking mods themselves will frequently load after RND which again causes massive issues with food not being marked by RND

**Comment by WrinklyNinja** [comment]
So RND needs to load after these cooking/food mods, but the patches are OK where they are?

Also, the proper place for this report would be [here](https://github.com/loot/skyrim/issues).

**Comment by mikeloeven** [comment]
RND loads after all Cooking and dlc patches for said cooking mods and the RND compatibility patches need to load after RND

**Comment by WrinklyNinja** [comment]
> RND loads after all Cooking and dlc patches for said cooking mods and the RND compatibility patches need to load after RND

I'm still not clear on what needs to change.

**Comment by LuthienKess** [comment]
I just tried sorting a few of the more common cooking mods to see if I could re-create the problem. 

* Cooking Expanded was mostly fine, a couple compatibility patches could be re-ordered, but it only affected about a dozen items. 
* Gromits Cooking Recipies wasn't compatible at all, and I couldn't find a compatibility patch.
* Babettes Feast, when used with the RND patch on the RND page, as described in the installer (That is, don't have the original Babette esp active, just load textures/meches) works just fine, no incompatibilities.

So, I couldn't find anything matching your description. Which cooking mod are you having trouble with?

**Comment by Freso** [comment]
This is an issue for the Skyrim masterlist, which has a separate bug tracker at https://github.com/loot/skyrim/issues – please report this issue there instead. Thank you.
