### ISSUE TITLE
Overhaul location metadata structure

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot.github.io#38]
Firstly, specifying versions is not very useful, because typically only the latest version is of interest, and having multiple possible versions complicates potential usage of the URLs.

I think it would be more useful to just assume that all given URLs are for the latest version, because when adding a link, it's easy enough to check whether the others are still valid, and if they become invalid and nobody checks them, it's no different to the current situation.

Secondly, having some way to name URLs could be handy, to distinguish between different mirrors perhaps, or differences such as translated versions. I'm not sure about this yet, since it's a bit dependent on how the information might be used. Possibilities include:

* "Open at ..." options for plugins with URLs.
* Tying the URLs to a mod name, with possible utility in features like whenever that name is mentioned in a message, it gets turned into a hyperlink automatically, eg. "Use the Unofficial Skyrim Patch instead" would turn into "Use the [Unofficial Skyrim Patch](http://www.nexusmods.com/skyrim/mods/19/?) instead".

Maybe add optional `site` and `mod` keys for those?

@loot/looters: Unless there are any objections, please don't add any more `url` entries with `ver` keys, ie. only use the [simple form](https://loot.github.io/docs/0.7.0/LOOT%20Metadata%20Syntax.html#structs-location) of the location metadata structure. If you want to label a URL, use a comment until I've figured out a more rigorous solution.

**Comment by egocarib** [comment]
I agree that version info isn't very useful for `url` entries.

The "Open at..." idea is cool. My only reservation is the fact that people are unlikely to report more than one location in most cases (and looters are unlikely to go check more than one location either). That's not to say it shouldn't be implemented - it would be a cool feature especially for the big hitters like the Unofficial Patch.

Auto-hyperlinking might also be nice, but I'd only support that if it's going to be relatively straightforward without adding a lot of complexity. It's easy enough to add those links where they're needed, and usually any link we'd want to go out of our way to make a `site` or `mod` tag for is already likely to be embedded in an alias.

**Comment by WrinklyNinja** [comment]
> The "Open at..." idea is cool. My only reservation is the fact that people are unlikely to report more than one location in most cases (and looters are unlikely to go check more than one location either).

Yeah, but the rationale is that some mods get hosted with multiple mirrors, and it's good to store that info in case one site disappears or the author decides to stop hosting on a site.

Of course, an implementation might just pick the first URL in the list to use, but at least if it goes bad there's just some shuffling to do. I dunno, this is all pretty hypothetical still.

And yeah, auto hyperlinking would add significant complexity, I think, but again, hypothetical, just grasping at straws for how to make the metadata useful to users, TBH. Links are only mildly useful if you've already got the mod, so it would be nice if the links you've stored can be used in other plugin's messages, etc. It could help cut down on data redundancy too.

Auto-hyperlinking for requirements would probably be a lot simpler though, you'd just look up each plugin directly and check if there are any URLs for it.

**Comment by Sharlikran** [comment]
For my patches I have some of them set up with version numbers because there are multiple files at one link.  Also because the intent of the message is to say if you don't have this version, then the file was made prior to the CK or has other undesirable issues.

If changing the way we present the information needs to change then I'm all for it.  I'm happy just limiting my usage of version numbers in relation to URls for the newest or latest version--if that's what's best.

**Comment by Freso** [comment]
+1 to adding "names"/descriptors of some sort to `url`s.
+0 to removing 'ver`. (Ie., I'm not for nor against that.)

**Comment by William-Imm** [comment]
I would like to see name/descriptors for URLs myself.

**Comment by egocarib** [comment]
Another Yea for names/descriptors.
And this sounds like a good idea:
>Auto-hyperlinking for requirements would probably be a lot simpler though, you'd just look up each plugin directly and check if there are any URLs for it.

**Comment by WrinklyNinja** [comment]
Re-posting this here for greater visibility:

In LOOT v0.8, the `ver` key will be removed, and a `name` key added (it takes a string value). You *can* use the name key immediately, it'll just get ignored by current versions of LOOT. This may be useful if you want to start naming URLs right away.

**Comment by WrinklyNinja** [comment]
Now in the latest `dev` code, so closing this.
