### ISSUE TITLE
"blue and purple backgrounds" = blue backgrounds

### ISSUE THREAD

**Issue by Freso** [loot/loot.github.io#46]
Looking at https://loot.github.io/credits/, I only see blue backgrounds for (public) team members, not purple ones for @WrinklyNinja and myself (the third admin currently has their team membership set to private).

Maybe it's my browser messing with the page (Firefox 41.0.2 on Linux) or my display being weird (old laptop LCD doesn't always distinguish well between colours), but maybe it's that right now something in the credit.js logic doesn't properly tell admins apart from "regular" members.

I don't know if we need the admin distinction though. Maybe we could just go with it and just have:

> Team members have blue backgrounds.

**Comment by WrinklyNinja** [comment]
Yeah, the logic is currently broken, and I think with GitHub's recent
organisation shake-up (which may have done the breaking...) the distinction
isn't as useful any more as there's more transparency anyway.

**Comment by WrinklyNinja** [comment]
In fact, I think I'll get rid of the member highlighting altogether. If anyone wants to know, they can see the list [here](https://github.com/orgs/loot/people) after all.
