### ISSUE TITLE
Search not working conistently

### ISSUE THREAD

**Issue by koumdros** [loot/loot.github.io#47]
I've been having this issue since level 8,0 and it is the same with 8.1

Usually if i try to search for a term ( usually a word contained within an eps's name ) it sometimes finds the first instance of that word, and doesnt find anything else, or doenst actually seem to do anything.

Sometimes the right hand panel ( with the esp modules) seemingly refreshes, but the reults dont actually have the word I;m searching for, in fact it seems all the esps are there ..
Othertimes everything works normally..

is there a way to increase loging verbocity to get more visibility?

**Comment by WrinklyNinja** [comment]
Closing this as invalid, as the issue should be tracked in the code issue tracker. I'll reply in the replacement issue linked above.
