### ISSUE TITLE
Make wiki hosted as part of the LOOT site

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot.github.io#51]
The separation of some information as pages in the wiki and other information as pages in the website is pretty arbitrary, and confers no advantages. It would be better for consistent look 'n' feel at least if the wiki pages were made part of the website.

Things that need to be done:

- [x] Move wiki pages into the website repository
- Update links to point to the website instead of the wiki in:
  - [x] LOOT's readme
  - [x] The `loot` repository's `README.md` and `CONTRIBUTING.md`
  - [x] Each masterlist repository's `CONTRIBUTING.md`

**Comment by Freso** [comment]
Did you already start work on this? If not, this is something I can try and poke at. :)

**Comment by WrinklyNinja** [comment]
No, I've not started it and probably won't get round to it this week, so
feel free to create a new branch and give it a go.

**Comment by WrinklyNinja** [comment]
@Freso have you done anything with this?

**Comment by Freso** [comment]
I started poking at it, yeah, and then I got distracted. :)

**Comment by Freso** [comment]
I want to do things the "hard" way to maintain history from the wiki, which means that the initial setup of porting over the articles is probably the hardest part of it.

**Comment by WrinklyNinja** [comment]
Yeah, that is tricky. If you do that, you'll need to rewrite file paths. While the wiki has a flat structure, the site would be better organised with the pages in folders: do you have any ideas for this?

I was thinking something along the lines of having `/docs/contributing/` holding the pages under the sidebar's "Contributing" heading and `/docs/team/` holding the pages under the "Team" heading. 

I'm not sure about the pages under the "General" heading, maybe `/docs/help/`, since they could all be described as "useful info" pages?

**Comment by Freso** [comment]
I was thinking to first do a merge to bring the two repositories together, leaving the wiki pages in a /wiki/ or /docs/ subdir and then follow up with additional commits `git mv`'ing the pages to the proper locations (incl. filenames) and then additional commits after that if they need additional edits for tidying up.

**Comment by WrinklyNinja** [comment]
Sounds good to me.

**Comment by WrinklyNinja** [comment]
I merged and mv'd the wiki in my local repository, and I've found that Jekyll won't turn Markdown into HTML unless it's a file in the `_posts` subdirectory, which is only really suitable for blog posts (they must be dated in the filename, and a few other restrictions).

This makes things inconvenient, as it means the wiki pages will need converting to HTML, but I think having everything in one place is still worth the increased verbosity. What do you think?

**Comment by WrinklyNinja** [comment]
I used Pandoc to convert the Markdown files to HTML, and pushed a `merged-wiki` branch with these converted wiki pages.

Some styling changes need to be made to ensure they look good (headings are too large, monospaced text needs a different background to help distinguish it, etc.), and navigation links to the new pages need to be added.

**Comment by WrinklyNinja** [comment]
Right, I've pushed the changes I mentioned were needed above. I've noticed some content is outdated, so that should be updated, and improving the readability of the auto-generated HTML would be useful.

**Comment by WrinklyNinja** [comment]
All that remains is for the wiki to be disabled in this repository's settings: that should be done after v0.9.0's release, because there are some readme links in v0.8.1 that link to the wiki.

**Comment by WrinklyNinja** [comment]
The wiki has been disabled, so closing this.
