### ISSUE TITLE
Masterlist won't update if user temp folder changed

### ISSUE THREAD

**Issue by damnsalvation** [loot/loot.github.io#53]
I had the user environment TEMP and TMP variables set to G:\UserTemp\Local\Temp
Opened loot to order skyrim, which I had just reinstalled.  Tried to update masterlist, got a filesystem access error.  Forget the exact error, but it was a 'could not modify' listing directories:
      C:\Users\...\LOOT\skyrim
      G:\UserTemp\Local\Temp\{random}

procmon showed LOOT.exe tried to open G:\UserTemp\Local\Temp\{random}, and was denied because it didn't exist

From Log:
      [0409/171435:ERROR:main_delegate.cc(738)] Could not load cef_extensions.pak

Since it looked like look was trying to use a generated temp folder, but without actually creating it first, I changed my TEMP and TMP variables back to the defaults.  It worked.  Masterlist updated just fine.  Then I realized I should report the bug so I thought I'd change the variables back to get the exact error that popped up.  But it didn't.  Not sure why, maybe because it didn't need to update again.
It's a pretty rare set of circumstances, so not exactly a high priority.

**Comment by damnsalvation** [comment]
Oh, all permissions are/were correct.

**Comment by WrinklyNinja** [comment]
Could you please re-file this [here](https://github.com/loot/loot/issues)? This issue tracker is for the site and meta issues, keeping application issues in its code repository helps keep everything organised.

**Comment by damnsalvation** [comment]
Oops!

**Comment by WrinklyNinja** [comment]
Re-filed as loot/loot#561, so closing this.
