### ISSUE TITLE
@Kaenguru-Knobel-Kette breaks credits page :)

### ISSUE THREAD

**Issue by Freso** [loot/loot.github.io#60]
@Kaenguru-Knobel-Kette's listing on https://loot.github.io/credits/ is broken:
![billede](https://user-images.githubusercontent.com/177659/27914846-b144afd2-6264-11e7-8ccd-33912491c8fe.png)

**Comment by WrinklyNinja** [comment]
Darn, I'll take a look at it.

**Comment by WrinklyNinja** [comment]
Fixed in a06cf6b5bf1e5705eadcba05f56c4bdfca6da690.
