### ISSUE TITLE
Update LOOT-FAQs.html

### ISSUE THREAD

**Issue by pStyl3** [loot/loot.github.io#71]
Within the "Using LOOT" section we still reference priority values, instead of groups.
`Priority values can be used when the plugin needs to load before or after many other plugins.`

Furthermore, the file references a readme that doesn't exist in that form.
`Be sure to read LOOT's readme for more information on these.`

The readme reference should probably be changed to mentioning the application documentation on readthedocs.

**Comment by Ortham** [comment]
Done in b4c58251e7834cbacd3c1436d25adc256a593ead, thanks for noticing that.
