### ISSUE TITLE
Incorrect path for Help docs

### ISSUE THREAD

**Issue by MacSplody** [loot/loot.github.io#72]
![image](https://user-images.githubusercontent.com/1944639/99191627-b2cea780-2765-11eb-8fc0-3b0eb578b81e.png)

Links on page https://loot.github.io/docs/help/
Help is included twice in the links.

https://loot.github.io/docs/help/help/LOOT-FAQs.html

**Comment by Ortham** [comment]
Fixed in 1f1d72b78cf0d87cd5f0071953945acac216d649.
