### ISSUE TITLE
Update FAQs

### ISSUE THREAD

**Issue by pStyl3** [loot/loot.github.io#79]
loot.github.io/docs/help/LOOT-FAQs.html

**I'm getting Git errors when LOOT tries to update its masterlist. How do I fix this?**
[...]
Alternatively, your WinSock configuration may be corrupt: this can be fixed using the instructions here and here, or there's a fix-it utility here.
[...]

Behind the 3 `here`'s are the following links:
`https://support.microsoft.com/kb/817571`
`https://support.microsoft.com/kb/318584`
`http://h10025.www1.hp.com/ewfrf/wc/document?cc=uk&lc=en&docname=c01184567`

Each of them seems to be dead, therefore we should update this bullet point, either by linking to different sites or by rewriting the answer.

Additionally:
> If LOOT still can't update its masterlist, you can update manually by downloading this file and placing it in the %LOCALAPPDATA%\LOOT\Skyrim folder. [...]

`this file` links to `https://raw.githubusercontent.com/loot/skyrim/v0.10/masterlist.yaml`

We probably should change that to
`https://raw.githubusercontent.com/loot/skyrim/v0.15/masterlist.yaml`.

**Comment by sibir-ine** [comment]
The first 2 links don't appear to exist anymore in Microsoft's current support database. The closest is [this article](https://support.microsoft.com/en-us/topic/how-to-determine-and-to-recover-from-winsock2-corruption-in-windows-server-2003-in-windows-xp-and-in-windows-vista-a6663bfa-40d1-ead7-d790-7869ee9448e7), but I'm not familiar with the issue; I don't know if the solutions there apply.

No clue about the 3rd link, it's not on the Archive.org. If the above article is enough, we can probably just remove it without replacing.

**Comment by Ortham** [comment]
I can't remember what the winsock fix actually was, but the article linked to by @sibir-ine isn't ringing any bells. The source issue is https://github.com/loot/loot/issues/352, which is from 2014, so I think it would be better to just to drop the line about WinSock.

**Comment by sibir-ine** [comment]
Done. Fixed a few typos & updated some other things I caught as well.
