### ISSUE TITLE
Reword masterlist Contributing readmes

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot.github.io#88]
I mentioned this in the Discord a while ago, but it completely slipped my mind. I'll file this issue so it doesn't get lost again.

I noticed this paragraph in the Contributing readme for the masterlists:

> If you send a pull request, then discover that you have made a mistake and make additional commits to fix it, please squash those additional commits to keep the commit history tidy. If you squash your commits, you don't need to open a new pull request. If you don't know how to squash commits, whoever merges your pull request can do it for you.

Since we just squash PRs on merge & don't really worry about contributors keeping them tidy, I think we should change it to something like:

> If you send a pull request, then discover that you have made a mistake, feel free to make additional commits to fix it. You don't need to squash your commits or open a new pull request to keep your commit history tidy; whoever merges your pull request can squash it for you. You can also mark your pull request as a draft if it isn't ready to be merged.

If anyone has any suggestions or concerns, please do let me know.

**Comment by sibir-ine** [comment]
@Ortham I've just noticed this line as well:

> (an offline copy is also available in the `docs` folder of each LOOT release)

referring to the docs on [metadata syntax](https://loot-api.readthedocs.io/en/stable/metadata/introduction.html). However, those docs don't appear to be packaged with LOOT. Should this line be removed, or can/should these docs be packaged with LOOT as well?

**Comment by Ortham** [comment]
That must be a leftover before libloot was split into a separate repository. I'd just remove the text, though we could potentially repackage the docs from libloot - it's easier just to point to the online docs though.
